### Test User Creation
POST http://localhost:8081/users
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "User",
  "email": "test.user@example.com",
  "password": "TestPassword123!",
  "passwordConfirm": "TestPassword123!",
  "dateOfBirth": "1990-01-01",
  "gender": "M",
  "height": 180,
  "weight": 75
}

### Get All Users (to verify creation)
GET http://localhost:8081/users

### Delete Test User (replace USER_ID_HERE with the actual ID from creation response)
DELETE http://localhost:8081/users/684ba167e106731a006b2f75

### Test that user login actually gives usable JWT
POST http://localhost:8081/users/login
Content-Type: application/json

{
    "email": "test.user@example.com", 
    "password": "TestPassword123!"
}